# Generated by Django 5.0 on 2023-12-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Короткое наименование')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип заказа')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255, verbose_name='Разнообразие')),
            ],
            options={
                'verbose_name': 'разнообразие заказов',
                'verbose_name_plural': 'разнообразия заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiker', models.CharField(max_length=255, verbose_name='Краткое название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.currency', verbose_name='Валюта')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordertype', verbose_name='Тип заказа')),
                ('order_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordervariety', verbose_name='Разнообразие заказов')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
